spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hello-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  hello:
    topic: hello-topic

server:
  port: 8081